name: swim-backend
dependencies:
- python
- pytest
- pytest-cov
- Flask
- Flask-SQLAlchemy
- SQLAlchemy
- Werkzeug
- PyYAML
- redis
- pip:
  - mongoengine
  - requests
  - marshmallow
  - marshmallow-sqlalchemy
  - flask-migrate
